#!/usr/bin/env python3
"""Create a realistic local Trackio logbook example.

The script builds a fresh mock reproduction workspace, creates a logbook, and
adds notebook-style markdown, code, figure, and command-run cells. It is meant
to execute immediately as a demo of what an agent-maintained paper reproduction
logbook might look like.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
import textwrap
from pathlib import Path

from trackio import logbook

ROOT = Path(__file__).resolve().parent
DEFAULT_WORKSPACE = ROOT / "mock_logbook_session"
MARKER = ".mock_trackio_logbook_workspace"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Mock a full Trackio logbook session.")
    parser.add_argument(
        "--workspace",
        type=Path,
        default=DEFAULT_WORKSPACE,
        help=f"Directory to create/use. Default: {DEFAULT_WORKSPACE.name}",
    )
    parser.add_argument(
        "--keep-existing",
        action="store_true",
        help="Append to an existing generated workspace instead of resetting it.",
    )
    return parser.parse_args()


def reset_workspace(workspace: Path, keep_existing: bool) -> None:
    workspace = workspace.resolve()
    if workspace.exists() and not keep_existing:
        marker = workspace / MARKER
        if not marker.exists():
            raise SystemExit(
                f"Refusing to delete {workspace}: it was not created by this script. "
                f"Use --workspace with an empty/generated directory or --keep-existing."
            )
        shutil.rmtree(workspace)
    workspace.mkdir(parents=True, exist_ok=True)
    (workspace / MARKER).write_text("generated by mock_trackio_logbook_session.py\n")


def _shell_quote(value: str) -> str:
    if not value:
        return "''"
    safe = set("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-./:=,")
    if all(ch in safe for ch in value):
        return value
    return "'" + value.replace("'", "'\"'\"'") + "'"


def _highlight_command(text: str) -> str:
    return f"\033[1m\033[38;5;208m{text}\033[0m"


def plotly_figure_html(data: list[dict], layout: dict) -> str:
    spec = json.dumps({"data": data, "layout": layout})
    return (
        "<!DOCTYPE html>\n<html>\n<head>\n"
        '<meta charset="utf-8" />\n'
        '<script src="https://cdn.plot.ly/plotly-2.35.2.min.js"></script>\n'
        "<style>html, body { margin: 0; padding: 0; }</style>\n"
        "</head>\n<body>\n"
        '<div id="figure"></div>\n'
        "<script>\n"
        f"const spec = {spec};\n"
        'Plotly.newPlot("figure", spec.data, spec.layout, '
        "{displayModeBar: false, responsive: true});\n"
        "</script>\n</body>\n</html>"
    )


def write_file(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(textwrap.dedent(text).strip() + "\n", encoding="utf-8")


def seed_repro_files(workspace: Path) -> None:
    write_file(
        workspace / "configs" / "baseline.json",
        json.dumps(
            {
                "paper": "Chain-of-thought prompting reproduction",
                "dataset": "gsm8k-mini",
                "model": "mock-7b-instruct",
                "shots": 8,
                "temperature": 0.0,
                "seed": 13,
                "max_examples": 128,
            },
            indent=2,
        ),
    )
    write_file(
        workspace / "configs" / "self_consistency.json",
        json.dumps(
            {
                "paper": "Chain-of-thought prompting reproduction",
                "dataset": "gsm8k-mini",
                "model": "mock-7b-instruct",
                "shots": 8,
                "temperature": 0.7,
                "samples_per_problem": 20,
                "vote": "majority",
                "seed": 17,
                "max_examples": 128,
            },
            indent=2,
        ),
    )
    write_file(
        workspace / "scripts" / "run_baseline.py",
        """
        import json
        from pathlib import Path

        cfg = json.loads(Path("configs/baseline.json").read_text())
        print(f"model={cfg['model']} dataset={cfg['dataset']} shots={cfg['shots']}")
        print("exact_match=0.414")
        print("rationale_parse_rate=0.922")
        print("mean_tokens=184")
        print("job=https://huggingface.co/jobs/mock-org/cot-baseline-001")
        """,
    )
    write_file(
        workspace / "scripts" / "run_self_consistency.py",
        """
        import json
        from pathlib import Path

        cfg = json.loads(Path("configs/self_consistency.json").read_text())
        print(
            f"samples={cfg['samples_per_problem']} temperature={cfg['temperature']} "
            f"vote={cfg['vote']}"
        )
        print("exact_match=0.563")
        print("majority_margin_mean=0.31")
        print("cost_multiplier=18.6")
        print("dashboard=https://huggingface.co/spaces/mock-org/cot-trackio-dashboard")
        """,
    )
    write_file(
        workspace / "scripts" / "eval_error_buckets.py",
        """
        buckets = {
            "arithmetic slip": 18,
            "wrong equation": 11,
            "answer extraction": 7,
            "ambiguous question": 3,
        }
        for name, count in buckets.items():
            print(f"{name}: {count}")
        print("dominant_failure=arithmetic slip")
        """,
    )
    write_file(
        workspace / "results" / "accuracy_by_condition.csv",
        """
        condition,exact_match,parse_rate,cost_multiplier
        direct,0.297,0.981,1.0
        cot,0.414,0.922,1.4
        cot_self_consistency,0.563,0.917,18.6
        cot_no_rationales_in_context,0.351,0.944,1.2
        """,
    )
    write_file(
        workspace / "figures" / "accuracy_bars.html",
        plotly_figure_html(
            data=[
                {
                    "type": "bar",
                    "orientation": "h",
                    "y": ["Direct", "CoT", "Self-consistency"],
                    "x": [29.7, 41.4, 56.3],
                    "marker": {"color": ["#64748b", "#2563eb", "#16a34a"]},
                    "text": ["29.7%", "41.4%", "56.3%"],
                    "textposition": "outside",
                    "hovertemplate": "%{y}: %{x}%<extra></extra>",
                }
            ],
            layout={
                "title": {"text": "GSM8K-mini exact match by prompting condition"},
                "xaxis": {"range": [0, 70], "ticksuffix": "%"},
                "margin": {"l": 130, "r": 30, "t": 55, "b": 40},
                "height": 340,
            },
        ),
    )


def build_logbook(workspace: Path) -> None:
    py = sys.executable
    cwd = Path.cwd()
    os.chdir(workspace)
    try:
        proj = logbook.create_logbook("Mock CoT Reproduction Logbook")

        baselines = logbook.ensure_page(proj, "Baselines")
        logbook.add_markdown_cell(
            proj,
            baselines,
            "Goal: reproduce the main chain-of-thought claims from "
            "https://arxiv.org/abs/2201.11903 on a small GSM8K-style slice "
            "(https://github.com/openai/grade-school-math). The direct-answer "
            "prompt landed at 29.7% exact match. The CoT prompt improved to "
            "41.4%, but parse failures rose because several rationales ended "
            "without a clean final answer marker. Evaluated on a slice of "
            "https://huggingface.co/datasets/openai/gsm8k.",
            title="Baseline result",
        )
        logbook.run_and_log(
            proj,
            [py, "scripts/run_baseline.py"],
            page="Baselines",
            title="Execute baseline harness",
        )
        logbook.add_code_cell(
            proj,
            baselines,
            "Validated on 50 sampled generations: 46 parsed, 4 missing marker.",
            title="Parse final answer helper",
            code_text=(
                "def extract_final_answer(text):\n"
                "    marker = 'Therefore, the answer is'\n"
                "    if marker not in text:\n"
                "        return None\n"
                "    return text.split(marker, 1)[1].strip().rstrip('.')"
            ),
            language="python",
        )

        self_consistency = logbook.ensure_page(proj, "Self-consistency")
        logbook.run_and_log(
            proj,
            [py, "scripts/run_self_consistency.py"],
            page="Self-consistency",
            title="Run 20-sample majority vote",
        )
        logbook.add_markdown_cell(
            proj,
            self_consistency,
            "Self-consistency reached 56.3% exact match, a +14.9 point gain over "
            "single-sample CoT. The run is not yet the preferred recipe because it "
            "costs 18.6x more tokens on this slice. Sampling settings:\n\n"
            "````json\n"
            '{"samples_per_problem": 20, "temperature": 0.7, "vote": "majority"}\n'
            "````",
            title="Sampling tradeoff",
        )
        logbook.add_artifact_cell(
            proj,
            self_consistency,
            "cot-repro/self-consistency-generations:v2",
            size=734_000_000,
        )
        logbook.add_figure_cell(
            proj,
            self_consistency,
            html=Path("figures/accuracy_bars.html").read_text(encoding="utf-8"),
            raw=Path("results/accuracy_by_condition.csv").read_text(encoding="utf-8"),
            title="Accuracy comparison",
        )

        error_analysis = logbook.ensure_page(proj, "Error analysis")
        logbook.run_and_log(
            proj,
            [py, "scripts/eval_error_buckets.py"],
            page="Error analysis",
            title="Bucket failed CoT generations",
        )
        logbook.add_figure_cell(
            proj,
            error_analysis,
            html=plotly_figure_html(
                data=[
                    {
                        "type": "bar",
                        "x": [
                            "Arithmetic slip",
                            "Wrong equation",
                            "Answer extraction",
                            "Ambiguous question",
                        ],
                        "y": [18, 11, 7, 3],
                        "marker": {"color": "#f97316"},
                        "hovertemplate": "%{x}: %{y}<extra></extra>",
                    }
                ],
                layout={
                    "title": {"text": "Failure buckets across 39 misses"},
                    "yaxis": {"title": {"text": "count"}},
                    "margin": {"l": 60, "r": 30, "t": 55, "b": 70},
                    "height": 360,
                },
            ),
            raw=json.dumps(
                {
                    "arithmetic slip": 18,
                    "wrong equation": 11,
                    "answer extraction": 7,
                    "ambiguous question": 3,
                },
                indent=2,
            ),
            title="Failure bucket sketch",
        )
        logbook.add_markdown_cell(
            proj,
            error_analysis,
            "Decision: next iteration should test a calculator-style verifier before "
            "more sampling. Arithmetic slips are the largest bucket, so additional "
            "samples may repeat the same systematic error.",
            title="Next experiment decision",
        )

        ablations = logbook.ensure_page(
            proj, "Ablations", parent_slug="self-consistency"
        )
        logbook.add_code_cell(
            proj,
            ablations,
            "queue: 5 samples\nqueue: 10 samples\nqueue: 20 samples\nqueue: verifier rerank",
            title="Ablation TODO generator",
            code_text=(
                "ablations = ['5 samples', '10 samples', '20 samples', 'verifier rerank']\n"
                "for ablation in ablations:\n"
                "    print(f'queue: {ablation}')"
            ),
            language="python",
        )
        logbook.write_site_files(proj)
    finally:
        os.chdir(cwd)


def main() -> None:
    args = parse_args()
    workspace = args.workspace.resolve()
    reset_workspace(workspace, keep_existing=args.keep_existing)
    seed_repro_files(workspace)
    build_logbook(workspace)

    logbook_dir = workspace / ".trackio" / "logbook"
    print("\nMock logbook created.")
    print(f"Workspace: {workspace}")
    print(f"Logbook files: {logbook_dir}")
    read_command = f"trackio logbook read --path {_shell_quote(str(workspace))}"
    open_command = f"trackio logbook serve {_shell_quote(str(workspace))}"
    print(f"Read logbook with: {read_command}")
    print(_highlight_command(open_command))


if __name__ == "__main__":
    main()
