#!/usr/bin/env python3
"""Create a realistic local Trackio logbook example.

The script builds a fresh mock reproduction workspace, creates a logbook, and
adds notebook-style markdown, code, command-run cells, a Codex-style session
trace, and generated Workspace files. It is meant to execute immediately as a
demo of what an agent-maintained paper reproduction logbook might look like.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
import textwrap
from pathlib import Path

from trackio import logbook

ROOT = Path(__file__).resolve().parent
DEFAULT_WORKSPACE = ROOT / "mock_logbook_session"
MARKER = ".mock_trackio_logbook_workspace"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Mock a full Trackio logbook session.")
    parser.add_argument(
        "--workspace",
        type=Path,
        default=DEFAULT_WORKSPACE,
        help=f"Directory to create/use. Default: {DEFAULT_WORKSPACE.name}",
    )
    parser.add_argument(
        "--keep-existing",
        action="store_true",
        help="Append to an existing generated workspace instead of resetting it.",
    )
    return parser.parse_args()


def reset_workspace(workspace: Path, keep_existing: bool) -> None:
    workspace = workspace.resolve()
    if workspace.exists() and not keep_existing:
        marker = workspace / MARKER
        if not marker.exists():
            raise SystemExit(
                f"Refusing to delete {workspace}: it was not created by this script. "
                f"Use --workspace with an empty/generated directory or --keep-existing."
            )
        shutil.rmtree(workspace)
    workspace.mkdir(parents=True, exist_ok=True)
    (workspace / MARKER).write_text("generated by mock_trackio_logbook_session.py\n")


def _shell_quote(value: str) -> str:
    if not value:
        return "''"
    safe = set("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-./:=,")
    if all(ch in safe for ch in value):
        return value
    return "'" + value.replace("'", "'\"'\"'") + "'"


def _highlight_command(text: str) -> str:
    return f"\033[1m\033[38;5;208m{text}\033[0m"


def write_file(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(textwrap.dedent(text).strip() + "\n", encoding="utf-8")


def accuracy_comparison_figure() -> tuple[str, str]:
    """Return a dependency-free SVG figure and its underlying data."""
    data = [
        {"method": "Direct answer", "exact_match": 29.7},
        {"method": "Chain of thought", "exact_match": 41.4},
        {"method": "Self-consistency", "exact_match": 56.3},
    ]
    html = """
    <figure style="margin:0;padding:8px 4px;font-family:system-ui,sans-serif;color:#1f2937">
      <figcaption style="margin:0 0 12px;font-size:14px;font-weight:650">
        Exact-match accuracy by prompting method
      </figcaption>
      <svg viewBox="0 0 760 280" role="img"
           aria-label="Horizontal bar chart comparing exact-match accuracy"
           style="display:block;width:100%;height:auto">
        <g fill="none" stroke="#e5e7eb" stroke-width="1">
          <path d="M190 28V238M350 28V238M510 28V238M670 28V238" />
        </g>
        <g fill="#6b7280" font-size="12" text-anchor="middle">
          <text x="190" y="260">0%</text>
          <text x="350" y="260">20%</text>
          <text x="510" y="260">40%</text>
          <text x="670" y="260">60%</text>
        </g>
        <g font-size="14">
          <text x="174" y="69" text-anchor="end" fill="#4b5563">Direct answer</text>
          <rect x="190" y="45" width="237.6" height="36" rx="6" fill="#fed7aa" />
          <text x="438" y="69" fill="#9a3412" font-weight="650">29.7%</text>

          <text x="174" y="139" text-anchor="end" fill="#4b5563">Chain of thought</text>
          <rect x="190" y="115" width="331.2" height="36" rx="6" fill="#fb923c" />
          <text x="532" y="139" fill="#9a3412" font-weight="650">41.4%</text>

          <text x="174" y="209" text-anchor="end" fill="#4b5563">Self-consistency</text>
          <rect x="190" y="185" width="450.4" height="36" rx="6" fill="#ea580c" />
          <text x="651" y="209" fill="#9a3412" font-weight="650">56.3%</text>
        </g>
      </svg>
    </figure>
    """
    return textwrap.dedent(html).strip(), json.dumps(data, indent=2)


def seed_repro_files(workspace: Path) -> None:
    write_file(
        workspace / "configs" / "baseline.json",
        json.dumps(
            {
                "paper": "Chain-of-thought prompting reproduction",
                "dataset": "gsm8k-mini",
                "model": "mock-7b-instruct",
                "shots": 8,
                "temperature": 0.0,
                "seed": 13,
                "max_examples": 128,
            },
            indent=2,
        ),
    )
    write_file(
        workspace / "configs" / "self_consistency.json",
        json.dumps(
            {
                "paper": "Chain-of-thought prompting reproduction",
                "dataset": "gsm8k-mini",
                "model": "mock-7b-instruct",
                "shots": 8,
                "temperature": 0.7,
                "samples_per_problem": 20,
                "vote": "majority",
                "seed": 17,
                "max_examples": 128,
            },
            indent=2,
        ),
    )
    write_file(
        workspace / "scripts" / "run_baseline.py",
        """
        import json
        from pathlib import Path

        cfg = json.loads(Path("configs/baseline.json").read_text())
        print(f"model={cfg['model']} dataset={cfg['dataset']} shots={cfg['shots']}")
        print("exact_match=0.414")
        print("rationale_parse_rate=0.922")
        print("mean_tokens=184")
        print("job=https://huggingface.co/jobs/mock-org/cot-baseline-001")

        out = Path("results/baseline/predictions.jsonl")
        out.parent.mkdir(parents=True, exist_ok=True)
        predictions = [
            {"id": "gsm8k-0007", "predicted": 18, "gold": 18, "correct": True},
            {"id": "gsm8k-0042", "predicted": 5, "gold": 7, "correct": False},
            {"id": "gsm8k-0113", "predicted": 120, "gold": 120, "correct": True},
        ]
        out.write_text("\\n".join(json.dumps(row) for row in predictions) + "\\n")
        print(f"wrote {out}")

        metrics = Path("results/baseline/metrics.csv")
        metrics.write_text(
            "metric,value\\nexact_match,0.414\\nrationale_parse_rate,0.922\\nmean_tokens,184\\n"
        )
        print(f"wrote {metrics}")
        """,
    )
    write_file(
        workspace / "scripts" / "run_self_consistency.py",
        """
        import json
        from pathlib import Path

        cfg = json.loads(Path("configs/self_consistency.json").read_text())
        print(
            f"samples={cfg['samples_per_problem']} temperature={cfg['temperature']} "
            f"vote={cfg['vote']}"
        )
        print("exact_match=0.563")
        print("majority_margin_mean=0.31")
        print("cost_multiplier=18.6")
        print("dashboard=https://huggingface.co/spaces/mock-org/cot-trackio-dashboard")

        out = Path("results/self_consistency/generations.jsonl")
        out.parent.mkdir(parents=True, exist_ok=True)
        generations = [
            {"id": "gsm8k-0007", "samples": 20, "votes": {"18": 13, "16": 5, "20": 2}, "final": 18},
            {"id": "gsm8k-0042", "samples": 20, "votes": {"7": 11, "5": 9}, "final": 7},
            {"id": "gsm8k-0113", "samples": 20, "votes": {"120": 17, "60": 3}, "final": 120},
        ]
        out.write_text("\\n".join(json.dumps(row) for row in generations) + "\\n")
        print(f"wrote {out}")

        margins = Path("results/self_consistency/vote_margins.csv")
        margins.write_text(
            "id,margin\\ngsm8k-0007,0.65\\ngsm8k-0042,0.10\\ngsm8k-0113,0.85\\n"
        )
        print(f"wrote {margins}")
        """,
    )
    write_file(
        workspace / "scripts" / "eval_error_buckets.py",
        """
        from pathlib import Path

        buckets = {
            "arithmetic slip": 18,
            "wrong equation": 11,
            "answer extraction": 7,
            "ambiguous question": 3,
        }
        for name, count in buckets.items():
            print(f"{name}: {count}")
        print("dominant_failure=arithmetic slip")

        out = Path("results/error_analysis/buckets.csv")
        out.parent.mkdir(parents=True, exist_ok=True)
        rows = ["bucket,count"] + [f"{name},{count}" for name, count in buckets.items()]
        out.write_text("\\n".join(rows) + "\\n")
        print(f"wrote {out}")
        """,
    )
    write_file(
        workspace / "scripts" / "run_verifier_rerank.py",
        """
        import json
        from pathlib import Path

        print("ablation=verifier_rerank base=self_consistency")
        print("exact_match=0.611")
        print("cost_multiplier=2.1")

        preds = Path("results/verifier/rerank_predictions.jsonl")
        preds.parent.mkdir(parents=True, exist_ok=True)
        reranked = [
            {"id": "gsm8k-0007", "before": 18, "after": 18, "verifier_score": 0.97},
            {"id": "gsm8k-0042", "before": 7, "after": 12, "verifier_score": 0.71},
            {"id": "gsm8k-0113", "before": 120, "after": 120, "verifier_score": 0.99},
        ]
        preds.write_text("\\n".join(json.dumps(row) for row in reranked) + "\\n")
        print(f"wrote {preds}")

        ckpt = Path("checkpoints/verifier/reranker.pt")
        ckpt.parent.mkdir(parents=True, exist_ok=True)
        ckpt.write_bytes(b"mock-verifier-weights\\n" * 512)
        print(f"wrote {ckpt}")
        """,
    )


def write_mock_trace(workspace: Path) -> Path:
    """Write a compact Codex-style rollout about building this demo logbook."""
    trace_path = workspace / "mock-codex-session.jsonl"
    session_id = "019b8f62-5a61-72d0-915f-cot-reproduction-demo"
    first_turn_id = "019b8f62-5a62-72d0-915f-c07ae0d00001"
    second_turn_id = "019b8f62-5a63-72d0-915f-c07ae0d00002"
    first_prompt = (
        "Build a Trackio logbook that reproduces the main chain-of-thought "
        "and self-consistency results on a small GSM8K-style evaluation slice."
    )
    second_prompt = (
        "Now run self-consistency and identify the most useful next experiment "
        "from the errors."
    )
    first_answer = (
        "I’ll establish the single-sample CoT baseline, then compare it with "
        "majority-vote sampling."
    )
    final_answer = (
        "The logbook now captures the baseline, the sampling tradeoff, the error "
        "analysis, and the verifier-rerank decision. The generated prediction "
        "and error files are available in Workspace."
    )

    def record(timestamp: str, kind: str, payload: dict) -> dict:
        return {"timestamp": timestamp, "type": kind, "payload": payload}

    records = [
        record(
            "2026-07-20T17:03:10.000Z",
            "session_meta",
            {
                "id": session_id,
                "timestamp": "2026-07-20T17:03:10.000Z",
                "cwd": str(workspace),
                "originator": "codex_cli_rs",
                "cli_version": "0.106.0",
                "source": "cli",
                "model_provider": "openai",
            },
        ),
        record(
            "2026-07-20T17:03:10.050Z",
            "turn_context",
            {"type": "turn_context", "model": "gpt-5-codex"},
        ),
        record(
            "2026-07-20T17:03:10.100Z",
            "event_msg",
            {"type": "task_started", "turn_id": first_turn_id},
        ),
        record(
            "2026-07-20T17:03:10.120Z",
            "response_item",
            {
                "type": "message",
                "role": "user",
                "content": [
                    {
                        "type": "input_text",
                        "text": first_prompt,
                    }
                ],
            },
        ),
        record(
            "2026-07-20T17:03:10.130Z",
            "event_msg",
            {
                "type": "user_message",
                "message": first_prompt,
                "images": [],
                "local_images": [],
                "text_elements": [],
            },
        ),
        record(
            "2026-07-20T17:03:12.400Z",
            "response_item",
            {
                "type": "reasoning",
                "summary": [
                    {
                        "type": "summary_text",
                        "text": (
                            "I should organize the work into Baselines, "
                            "Self-consistency, Error analysis, and Ablations. "
                            "First I will run the deterministic baseline and "
                            "record both the command and its interpretation."
                        ),
                    }
                ],
            },
        ),
        record(
            "2026-07-20T17:03:13.050Z",
            "response_item",
            {
                "type": "message",
                "role": "assistant",
                "content": [
                    {
                        "type": "output_text",
                        "text": first_answer,
                    }
                ],
            },
        ),
        record(
            "2026-07-20T17:03:13.060Z",
            "event_msg",
            {"type": "agent_message", "message": first_answer, "phase": "commentary"},
        ),
        record(
            "2026-07-20T17:03:13.300Z",
            "response_item",
            {
                "type": "function_call",
                "name": "exec_command",
                "call_id": "call_baseline",
                "arguments": json.dumps(
                    {"cmd": "python scripts/run_baseline.py", "yield_time_ms": 10000}
                ),
            },
        ),
        record(
            "2026-07-20T17:03:14.020Z",
            "response_item",
            {
                "type": "function_call_output",
                "call_id": "call_baseline",
                "output": (
                    "model=mock-7b-instruct dataset=gsm8k-mini shots=8\n"
                    "exact_match=0.414\n"
                    "rationale_parse_rate=0.922\n"
                    "mean_tokens=184\n"
                    "wrote results/baseline/predictions.jsonl"
                ),
            },
        ),
        record(
            "2026-07-20T17:03:16.200Z",
            "response_item",
            {
                "type": "reasoning",
                "summary": [
                    {
                        "type": "summary_text",
                        "text": (
                            "The baseline reaches 41.4% exact match but loses "
                            "some answers during final-answer parsing. I’ll log "
                            "that result in Markdown and preserve the extraction "
                            "helper as a code cell."
                        ),
                    }
                ],
            },
        ),
        record(
            "2026-07-20T17:03:17.100Z",
            "event_msg",
            {
                "type": "task_complete",
                "turn_id": first_turn_id,
                "last_agent_message": first_answer,
            },
        ),
        record(
            "2026-07-20T17:04:02.000Z",
            "event_msg",
            {"type": "task_started", "turn_id": second_turn_id},
        ),
        record(
            "2026-07-20T17:04:02.050Z",
            "response_item",
            {
                "type": "message",
                "role": "user",
                "content": [
                    {
                        "type": "input_text",
                        "text": second_prompt,
                    }
                ],
            },
        ),
        record(
            "2026-07-20T17:04:02.060Z",
            "event_msg",
            {
                "type": "user_message",
                "message": second_prompt,
                "images": [],
                "local_images": [],
                "text_elements": [],
            },
        ),
        record(
            "2026-07-20T17:04:04.600Z",
            "response_item",
            {
                "type": "function_call",
                "name": "exec_command",
                "call_id": "call_self_consistency",
                "arguments": json.dumps(
                    {
                        "cmd": "python scripts/run_self_consistency.py",
                        "yield_time_ms": 10000,
                    }
                ),
            },
        ),
        record(
            "2026-07-20T17:04:05.440Z",
            "response_item",
            {
                "type": "function_call_output",
                "call_id": "call_self_consistency",
                "output": (
                    "samples=20 temperature=0.7 vote=majority\n"
                    "exact_match=0.563\n"
                    "majority_margin_mean=0.31\n"
                    "cost_multiplier=18.6\n"
                    "wrote results/self_consistency/generations.jsonl"
                ),
            },
        ),
        record(
            "2026-07-20T17:04:07.000Z",
            "response_item",
            {
                "type": "function_call",
                "name": "exec_command",
                "call_id": "call_errors",
                "arguments": json.dumps(
                    {"cmd": "python scripts/eval_error_buckets.py"}
                ),
            },
        ),
        record(
            "2026-07-20T17:04:07.510Z",
            "response_item",
            {
                "type": "function_call_output",
                "call_id": "call_errors",
                "output": (
                    "arithmetic slip: 18\n"
                    "wrong equation: 11\n"
                    "answer extraction: 7\n"
                    "ambiguous question: 3\n"
                    "dominant_failure=arithmetic slip\n"
                    "wrote results/error_analysis/buckets.csv"
                ),
            },
        ),
        record(
            "2026-07-20T17:04:10.800Z",
            "response_item",
            {
                "type": "reasoning",
                "summary": [
                    {
                        "type": "summary_text",
                        "text": (
                            "Self-consistency improves exact match by 14.9 points "
                            "but costs 18.6x more tokens. Arithmetic slips remain "
                            "the largest error bucket, so a calculator-style "
                            "verifier is a better next ablation than more samples."
                        ),
                    }
                ],
            },
        ),
        record(
            "2026-07-20T17:04:12.000Z",
            "response_item",
            {
                "type": "message",
                "role": "assistant",
                "content": [
                    {
                        "type": "output_text",
                        "text": final_answer,
                    }
                ],
            },
        ),
        record(
            "2026-07-20T17:04:12.010Z",
            "event_msg",
            {"type": "agent_message", "message": final_answer, "phase": "final"},
        ),
        record(
            "2026-07-20T17:04:12.200Z",
            "event_msg",
            {
                "type": "task_complete",
                "turn_id": second_turn_id,
                "last_agent_message": final_answer,
            },
        ),
    ]
    trace_path.write_text(
        "\n".join(json.dumps(item, ensure_ascii=False) for item in records) + "\n",
        encoding="utf-8",
    )
    return trace_path


def write_mock_trace_verifier(workspace: Path) -> Path:
    """Write a shorter follow-up Codex session for the verifier-rerank ablation."""
    trace_path = workspace / "mock-codex-verifier.jsonl"
    session_id = "019b8f77-2c40-71a4-88ee-verifier-rerank-ablation"
    turn_id = "019b8f77-2c41-71a4-88ee-a811a7100001"
    prompt = (
        "Run the calculator-style verifier rerank ablation we queued and record "
        "whether it beats more sampling."
    )
    answer = (
        "Verifier rerank reaches 61.1% exact match at 2.1x cost — a better "
        "tradeoff than 20-sample self-consistency. The reranker checkpoint is "
        "saved under checkpoints/verifier."
    )

    def record(timestamp: str, kind: str, payload: dict) -> dict:
        return {"timestamp": timestamp, "type": kind, "payload": payload}

    records = [
        record(
            "2026-07-20T18:12:04.000Z",
            "session_meta",
            {
                "id": session_id,
                "timestamp": "2026-07-20T18:12:04.000Z",
                "cwd": str(workspace),
                "originator": "codex_cli_rs",
                "cli_version": "0.106.0",
                "source": "cli",
                "model_provider": "openai",
            },
        ),
        record(
            "2026-07-20T18:12:04.050Z",
            "turn_context",
            {"type": "turn_context", "model": "gpt-5-codex"},
        ),
        record(
            "2026-07-20T18:12:04.100Z",
            "event_msg",
            {"type": "task_started", "turn_id": turn_id},
        ),
        record(
            "2026-07-20T18:12:04.120Z",
            "response_item",
            {
                "type": "message",
                "role": "user",
                "content": [
                    {
                        "type": "input_text",
                        "text": prompt,
                    }
                ],
            },
        ),
        record(
            "2026-07-20T18:12:04.130Z",
            "event_msg",
            {
                "type": "user_message",
                "message": prompt,
                "images": [],
                "local_images": [],
                "text_elements": [],
            },
        ),
        record(
            "2026-07-20T18:12:06.300Z",
            "response_item",
            {
                "type": "reasoning",
                "summary": [
                    {
                        "type": "summary_text",
                        "text": (
                            "Arithmetic slips were the dominant error, so a verifier "
                            "that rescopes the final answer should help more than "
                            "extra samples. I'll rerank the self-consistency outputs."
                        ),
                    }
                ],
            },
        ),
        record(
            "2026-07-20T18:12:07.400Z",
            "response_item",
            {
                "type": "function_call",
                "name": "exec_command",
                "call_id": "call_verifier",
                "arguments": json.dumps(
                    {
                        "cmd": "python scripts/run_verifier_rerank.py",
                        "yield_time_ms": 10000,
                    }
                ),
            },
        ),
        record(
            "2026-07-20T18:12:09.900Z",
            "response_item",
            {
                "type": "function_call_output",
                "call_id": "call_verifier",
                "output": (
                    "ablation=verifier_rerank base=self_consistency\n"
                    "exact_match=0.611\n"
                    "cost_multiplier=2.1\n"
                    "wrote results/verifier/rerank_predictions.jsonl\n"
                    "wrote checkpoints/verifier/reranker.pt"
                ),
            },
        ),
        record(
            "2026-07-20T18:12:12.100Z",
            "response_item",
            {
                "type": "message",
                "role": "assistant",
                "content": [
                    {
                        "type": "output_text",
                        "text": answer,
                    }
                ],
            },
        ),
        record(
            "2026-07-20T18:12:12.110Z",
            "event_msg",
            {"type": "agent_message", "message": answer, "phase": "final"},
        ),
        record(
            "2026-07-20T18:12:12.400Z",
            "event_msg",
            {
                "type": "task_complete",
                "turn_id": turn_id,
                "last_agent_message": answer,
            },
        ),
    ]
    trace_path.write_text(
        "\n".join(json.dumps(item, ensure_ascii=False) for item in records) + "\n",
        encoding="utf-8",
    )
    return trace_path


def build_logbook(workspace: Path) -> None:
    py = sys.executable
    cwd = Path.cwd()
    os.chdir(workspace)
    try:
        proj = logbook.create_logbook("Mock CoT Reproduction Logbook")
        trace_path = write_mock_trace(workspace)
        logbook.attach_trace(
            proj,
            trace_path,
            title="CoT reproduction session",
        )
        verifier_trace_path = write_mock_trace_verifier(workspace)
        logbook.attach_trace(
            proj,
            verifier_trace_path,
            title="Verifier rerank ablation",
        )

        baselines = logbook.ensure_page(proj, "Baselines")
        logbook.add_markdown_cell(
            proj,
            baselines,
            "Goal: reproduce the main chain-of-thought claims from "
            "https://arxiv.org/abs/2201.11903 on a small GSM8K-style slice "
            "(https://github.com/openai/grade-school-math). The direct-answer "
            "prompt landed at 29.7% exact match. The CoT prompt improved to "
            "41.4%, but parse failures rose because several rationales ended "
            "without a clean final answer marker. Evaluated on a slice of "
            "https://huggingface.co/datasets/openai/gsm8k.",
            title="Baseline result",
        )
        logbook.set_cell_pinned(
            proj, logbook.last_cell_id(proj, baselines), page=baselines
        )
        logbook.run_and_log(
            proj,
            [py, "scripts/run_baseline.py"],
            page="Baselines",
            title="Execute baseline harness",
        )
        logbook.add_code_cell(
            proj,
            baselines,
            "Validated on 50 sampled generations: 46 parsed, 4 missing marker.",
            title="Parse final answer helper",
            code_text=(
                "def extract_final_answer(text):\n"
                "    marker = 'Therefore, the answer is'\n"
                "    if marker not in text:\n"
                "        return None\n"
                "    return text.split(marker, 1)[1].strip().rstrip('.')"
            ),
            language="python",
        )

        self_consistency = logbook.ensure_page(proj, "Self-consistency")
        logbook.run_and_log(
            proj,
            [py, "scripts/run_self_consistency.py"],
            page="Self-consistency",
            title="Run 20-sample majority vote",
        )
        logbook.add_markdown_cell(
            proj,
            self_consistency,
            "Self-consistency reached 56.3% exact match, a +14.9 point gain over "
            "single-sample CoT. The run is not yet the preferred recipe because it "
            "costs 18.6x more tokens on this slice. Sampling settings:\n\n"
            "````json\n"
            '{"samples_per_problem": 20, "temperature": 0.7, "vote": "majority"}\n'
            "````",
            title="Sampling tradeoff",
        )
        figure_html, figure_data = accuracy_comparison_figure()
        logbook.add_figure_cell(
            proj,
            self_consistency,
            html=figure_html,
            raw=figure_data,
            title="Accuracy comparison",
        )

        error_analysis = logbook.ensure_page(proj, "Error analysis")
        logbook.run_and_log(
            proj,
            [py, "scripts/eval_error_buckets.py"],
            page="Error analysis",
            title="Bucket failed CoT generations",
        )
        logbook.add_markdown_cell(
            proj,
            error_analysis,
            "Decision: next iteration should test a calculator-style verifier before "
            "more sampling. Arithmetic slips are the largest bucket, so additional "
            "samples may repeat the same systematic error.",
            title="Next experiment decision",
        )

        ablations = logbook.ensure_page(proj, "Ablations")
        logbook.add_code_cell(
            proj,
            ablations,
            "queue: 5 samples\nqueue: 10 samples\nqueue: 20 samples\nqueue: verifier rerank",
            title="Ablation TODO generator",
            code_text=(
                "ablations = ['5 samples', '10 samples', '20 samples', 'verifier rerank']\n"
                "for ablation in ablations:\n"
                "    print(f'queue: {ablation}')"
            ),
            language="python",
        )
        logbook.run_and_log(
            proj,
            [py, "scripts/run_verifier_rerank.py"],
            page="Ablations",
            title="Verifier rerank ablation",
        )
        logbook.write_site_files(proj)
    finally:
        os.chdir(cwd)


def main() -> None:
    args = parse_args()
    workspace = args.workspace.resolve()
    reset_workspace(workspace, keep_existing=args.keep_existing)
    seed_repro_files(workspace)
    build_logbook(workspace)

    logbook_dir = workspace / ".trackio" / "logbook"
    print("\nMock logbook created.")
    print(f"Workspace: {workspace}")
    print(f"Logbook files: {logbook_dir}")
    print(f"Mock traces: {workspace / 'mock-codex-session.jsonl'}")
    print(f"             {workspace / 'mock-codex-verifier.jsonl'}")
    read_command = f"trackio logbook read --path {_shell_quote(str(workspace))}"
    open_command = f"trackio logbook serve {_shell_quote(str(workspace))}"
    print(f"Read logbook with: {read_command}")
    print(_highlight_command(open_command))


if __name__ == "__main__":
    main()
