#!/usr/bin/env python3
"""Create a realistic local Trackio logbook by repeatedly calling the CLI.

The script builds a fresh mock reproduction workspace, creates a logbook, and
adds notebook-style markdown, code, figure, and command-run cells. It is meant
to execute immediately as a demo of what an agent-maintained paper reproduction
logbook might look like.
"""

from __future__ import annotations

import argparse
import json
import shlex
import shutil
import socket
import subprocess
import sys
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DEFAULT_WORKSPACE = ROOT / "mock_logbook_session"
MARKER = ".mock_trackio_logbook_workspace"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Mock a full Trackio logbook session using the trackio CLI."
    )
    parser.add_argument(
        "--workspace",
        type=Path,
        default=DEFAULT_WORKSPACE,
        help=f"Directory to create/use. Default: {DEFAULT_WORKSPACE.name}",
    )
    parser.add_argument(
        "--keep-existing",
        action="store_true",
        help="Append to an existing generated workspace instead of resetting it.",
    )
    parser.add_argument(
        "--trackio",
        default=shutil.which("trackio") or "trackio",
        help='Trackio command to run, e.g. "trackio" or "python -m trackio.cli".',
    )
    return parser.parse_args()


def reset_workspace(workspace: Path, keep_existing: bool) -> None:
    workspace = workspace.resolve()
    if workspace.exists() and not keep_existing:
        marker = workspace / MARKER
        if not marker.exists():
            raise SystemExit(
                f"Refusing to delete {workspace}: it was not created by this script. "
                f"Use --workspace with an empty/generated directory or --keep-existing."
            )
        shutil.rmtree(workspace)
    workspace.mkdir(parents=True, exist_ok=True)
    (workspace / MARKER).write_text("generated by mock_trackio_logbook_session.py\n")


def run_cli(
    trackio: list[str], workspace: Path, *args: str
) -> subprocess.CompletedProcess[str]:
    command = [*trackio, "logbook", *args]
    print("\n$ " + " ".join(_shell_quote(part) for part in command))
    result = subprocess.run(
        command,
        cwd=workspace,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
    if result.stdout:
        print(result.stdout.rstrip())
    if result.returncode != 0:
        raise SystemExit(f"Command failed with exit code {result.returncode}")
    return result


def refresh_static_site(trackio: list[str], workspace: Path) -> None:
    """Run the preview command briefly so logbook.json/logbook.md are refreshed."""
    with socket.socket() as sock:
        sock.bind(("127.0.0.1", 0))
        port = sock.getsockname()[1]

    command = [*trackio, "logbook", "serve", "--no-browser", "--port", str(port)]
    print("\n$ " + " ".join(_shell_quote(part) for part in command))
    try:
        result = subprocess.run(
            command,
            cwd=workspace,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            timeout=2,
            check=False,
        )
    except subprocess.TimeoutExpired as exc:
        output = exc.stdout or ""
        if output:
            print(output.rstrip())
        print("Stopped preview refresh.")
        return

    if result.stdout:
        print(result.stdout.rstrip())
    if result.returncode != 0:
        raise SystemExit(f"Command failed with exit code {result.returncode}")


def _shell_quote(value: str) -> str:
    if not value:
        return "''"
    safe = set("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-./:=,")
    if all(ch in safe for ch in value):
        return value
    return "'" + value.replace("'", "'\"'\"'") + "'"


def write_file(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(textwrap.dedent(text).strip() + "\n", encoding="utf-8")


def seed_repro_files(workspace: Path) -> None:
    write_file(
        workspace / "configs" / "baseline.json",
        json.dumps(
            {
                "paper": "Chain-of-thought prompting reproduction",
                "dataset": "gsm8k-mini",
                "model": "mock-7b-instruct",
                "shots": 8,
                "temperature": 0.0,
                "seed": 13,
                "max_examples": 128,
            },
            indent=2,
        ),
    )
    write_file(
        workspace / "configs" / "self_consistency.json",
        json.dumps(
            {
                "paper": "Chain-of-thought prompting reproduction",
                "dataset": "gsm8k-mini",
                "model": "mock-7b-instruct",
                "shots": 8,
                "temperature": 0.7,
                "samples_per_problem": 20,
                "vote": "majority",
                "seed": 17,
                "max_examples": 128,
            },
            indent=2,
        ),
    )
    write_file(
        workspace / "scripts" / "run_baseline.py",
        """
        import json
        from pathlib import Path

        cfg = json.loads(Path("configs/baseline.json").read_text())
        print(f"model={cfg['model']} dataset={cfg['dataset']} shots={cfg['shots']}")
        print("exact_match=0.414")
        print("rationale_parse_rate=0.922")
        print("mean_tokens=184")
        """,
    )
    write_file(
        workspace / "scripts" / "run_self_consistency.py",
        """
        import json
        from pathlib import Path

        cfg = json.loads(Path("configs/self_consistency.json").read_text())
        print(
            f"samples={cfg['samples_per_problem']} temperature={cfg['temperature']} "
            f"vote={cfg['vote']}"
        )
        print("exact_match=0.563")
        print("majority_margin_mean=0.31")
        print("cost_multiplier=18.6")
        """,
    )
    write_file(
        workspace / "scripts" / "eval_error_buckets.py",
        """
        buckets = {
            "arithmetic slip": 18,
            "wrong equation": 11,
            "answer extraction": 7,
            "ambiguous question": 3,
        }
        for name, count in buckets.items():
            print(f"{name}: {count}")
        print("dominant_failure=arithmetic slip")
        """,
    )
    write_file(
        workspace / "results" / "accuracy_by_condition.csv",
        """
        condition,exact_match,parse_rate,cost_multiplier
        direct,0.297,0.981,1.0
        cot,0.414,0.922,1.4
        cot_self_consistency,0.563,0.917,18.6
        cot_no_rationales_in_context,0.351,0.944,1.2
        """,
    )
    write_file(
        workspace / "figures" / "accuracy_bars.html",
        """
        <figure style="font-family: system-ui, sans-serif; max-width: 720px;">
          <figcaption style="font-weight: 700; margin-bottom: 12px;">
            GSM8K-mini exact match by prompting condition
          </figcaption>
          <div style="display: grid; gap: 10px;">
            <div>Direct <span style="display:inline-block;background:#64748b;width:178px;height:14px"></span> 29.7%</div>
            <div>CoT <span style="display:inline-block;background:#2563eb;width:248px;height:14px"></span> 41.4%</div>
            <div>Self-consistency <span style="display:inline-block;background:#16a34a;width:338px;height:14px"></span> 56.3%</div>
          </div>
        </figure>
        """,
    )


def build_logbook(workspace: Path, trackio: list[str]) -> None:
    py = sys.executable

    run_cli(trackio, workspace, "open", "--title", "Mock CoT Reproduction Logbook")

    run_cli(trackio, workspace, "page", "Campaign overview")
    run_cli(
        trackio,
        workspace,
        "cell",
        "markdown",
        (
            "Goal: reproduce the main chain-of-thought and self-consistency claims on "
            "a small GSM8K-style slice, then document which deltas survive under the "
            "same prompt budget. Planned pages cover baselines, sampling, error "
            "analysis, and final takeaways."
        ),
        "--title",
        "Reproduction plan",
        "--page",
        "Campaign overview",
        "--link",
        "https://arxiv.org/abs/2201.11903",
        "--link",
        "https://github.com/openai/grade-school-math",
    )
    run_cli(
        trackio,
        workspace,
        "cell",
        "markdown",
        (
            "| Experiment | Status | Decision |\n"
            "| --- | --- | --- |\n"
            "| Direct baseline | done | Use as floor for prompt formatting checks. |\n"
            "| CoT baseline | done | Primary target to beat. |\n"
            "| Self-consistency | in progress | Promising but cost-heavy. |\n"
            "| Error buckets | planned | Needed before deciding next ablation. |"
        ),
        "--title",
        "Campaign state table",
        "--page",
        "Campaign overview",
        "--artifact",
        "cot-repro/campaign-plan:v1",
    )

    run_cli(trackio, workspace, "page", "Baselines")
    run_cli(
        trackio,
        workspace,
        "cell",
        "markdown",
        (
            "The direct-answer prompt landed at 29.7% exact match. The CoT prompt "
            "improved to 41.4%, but parse failures rose because several rationales "
            "ended without a clean final answer marker."
        ),
        "--title",
        "Baseline result",
        "--page",
        "Baselines",
        "--code",
        "configs/baseline.json",
        "--code",
        "scripts/run_baseline.py",
        "--link",
        "https://huggingface.co/datasets/openai/gsm8k",
    )
    run_cli(
        trackio,
        workspace,
        "run",
        "--page",
        "Baselines",
        "--title",
        "Execute baseline harness",
        "--link",
        "https://huggingface.co/jobs/mock-org/cot-baseline-001",
        "--",
        py,
        "scripts/run_baseline.py",
    )
    run_cli(
        trackio,
        workspace,
        "cell",
        "code",
        "--title",
        "Parse final answer helper",
        "--page",
        "Baselines",
        "--code-text",
        (
            "def extract_final_answer(text):\n"
            "    marker = 'Therefore, the answer is'\n"
            "    if marker not in text:\n"
            "        return None\n"
            "    return text.split(marker, 1)[1].strip().rstrip('.')"
        ),
        "--language",
        "python",
        "--output",
        "Validated on 50 sampled generations: 46 parsed, 4 missing marker.",
    )

    run_cli(trackio, workspace, "page", "Self-consistency")
    run_cli(
        trackio,
        workspace,
        "run",
        "--page",
        "Self-consistency",
        "--title",
        "Run 20-sample majority vote",
        "--link",
        "https://huggingface.co/spaces/mock-org/cot-trackio-dashboard",
        "--",
        py,
        "scripts/run_self_consistency.py",
    )
    run_cli(
        trackio,
        workspace,
        "cell",
        "markdown",
        (
            "Self-consistency reached 56.3% exact match, a +14.9 point gain over "
            "single-sample CoT. The run is not yet the preferred recipe because it "
            "costs 18.6x more tokens on this slice."
        ),
        "--title",
        "Sampling tradeoff",
        "--page",
        "Self-consistency",
        "--code",
        "configs/self_consistency.json",
        "--artifact",
        "cot-repro/self-consistency-generations:v2",
    )
    run_cli(
        trackio,
        workspace,
        "cell",
        "figure",
        "--title",
        "Accuracy comparison",
        "--page",
        "Self-consistency",
        "--html",
        "figures/accuracy_bars.html",
        "--raw",
        "results/accuracy_by_condition.csv",
    )

    run_cli(trackio, workspace, "page", "Error analysis")
    run_cli(
        trackio,
        workspace,
        "run",
        "--page",
        "Error analysis",
        "--title",
        "Bucket failed CoT generations",
        "--",
        py,
        "scripts/eval_error_buckets.py",
    )
    run_cli(
        trackio,
        workspace,
        "cell",
        "figure",
        "--title",
        "Failure bucket sketch",
        "--page",
        "Error analysis",
        "--html-text",
        (
            "<div style='font-family: system-ui'>"
            "<strong>Failure buckets</strong>"
            "<ul><li>Arithmetic slip: 18</li><li>Wrong equation: 11</li>"
            "<li>Answer extraction: 7</li><li>Ambiguous question: 3</li></ul>"
            "</div>"
        ),
        "--raw-text",
        json.dumps(
            {
                "arithmetic slip": 18,
                "wrong equation": 11,
                "answer extraction": 7,
                "ambiguous question": 3,
            },
            indent=2,
        ),
    )
    run_cli(
        trackio,
        workspace,
        "cell",
        "markdown",
        (
            "Decision: next iteration should test a calculator-style verifier before "
            "more sampling. Arithmetic slips are the largest bucket, so additional "
            "samples may repeat the same systematic error."
        ),
        "--title",
        "Next experiment decision",
        "--page",
        "Error analysis",
    )

    run_cli(trackio, workspace, "page", "Ablations", "--parent", "self-consistency")
    run_cli(
        trackio,
        workspace,
        "cell",
        "code",
        "--title",
        "Ablation TODO generator",
        "--page",
        "Ablations",
        "--code-text",
        (
            "ablations = ['5 samples', '10 samples', '20 samples', 'verifier rerank']\n"
            "for ablation in ablations:\n"
            "    print(f'queue: {ablation}')"
        ),
        "--language",
        "python",
        "--output",
        "queue: 5 samples\nqueue: 10 samples\nqueue: 20 samples\nqueue: verifier rerank",
    )

    run_cli(trackio, workspace, "read", "pages", "--json")
    run_cli(trackio, workspace, "read", "page", "Self-consistency")
    refresh_static_site(trackio, workspace)


def main() -> None:
    args = parse_args()
    workspace = args.workspace.resolve()
    trackio = shlex.split(args.trackio)
    if not trackio:
        raise SystemExit("--trackio cannot be empty")
    reset_workspace(workspace, keep_existing=args.keep_existing)
    seed_repro_files(workspace)
    build_logbook(workspace, trackio)

    logbook_dir = workspace / ".trackio" / "logbook"
    print("\nMock logbook created.")
    print(f"Workspace: {workspace}")
    print(f"Logbook files: {logbook_dir}")
    print(f"Flattened agent view: {logbook_dir / 'logbook.md'}")
    open_command = (
        f"cd {_shell_quote(str(workspace))} && "
        f"{' '.join(_shell_quote(part) for part in trackio)} logbook serve"
    )
    print(f"Open logbook with: {open_command}")


if __name__ == "__main__":
    main()
