from __future__ import annotations

import json
import re
import shutil
from datetime import datetime, timezone
from pathlib import Path

PROJECT_DIR_NAME = ".trackio"
LOGBOOK_SUBDIR = "logbook"
METADATA_FILE = "metadata.json"
SCHEMA_VERSION = 1
ROOT_SLUG = "index"
VIEWER_DIR = Path(__file__).parent / "frontend_templates" / "logbook"
VIEWER_FILES = ["index.html", "logbook.css", "logbook.js", "trackio-logo.png"]

EXP_HEADER = "| Status | Experiment |"
EXP_SEP = "| --- | --- |"


class LogbookError(Exception):
    pass


def _now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def _human_time(iso: str) -> str:
    try:
        dt = datetime.fromisoformat(iso)
    except ValueError:
        return iso
    return dt.strftime("%b %d, %Y · %H:%M UTC")


def _slugify(text: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", text.strip().lower()).strip("-")
    return slug or "page"


# ---- locating the project ----


def find_project_dir(start: str | Path | None = None) -> Path | None:
    start = Path(start or Path.cwd()).resolve()
    for d in (start, *start.parents):
        candidate = d / PROJECT_DIR_NAME
        if (candidate / LOGBOOK_SUBDIR / "pages" / "index.md").is_file():
            return candidate
    return None


def require_project_dir() -> Path:
    proj = find_project_dir()
    if proj is None:
        raise LogbookError(
            "No logbook in this directory (or any parent). "
            "Start one with: trackio logbook open [SPACE_ID]"
        )
    return proj


def logbook_root(proj: Path) -> Path:
    return proj / LOGBOOK_SUBDIR


def _pages_dir(proj: Path) -> Path:
    return logbook_root(proj) / "pages"


def _metadata_path(proj: Path) -> Path:
    return proj / METADATA_FILE


def read_metadata(proj: Path) -> dict:
    path = _metadata_path(proj)
    if not path.is_file():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def write_metadata(proj: Path, metadata: dict) -> None:
    _metadata_path(proj).write_text(
        json.dumps(metadata, indent=2, ensure_ascii=False), encoding="utf-8"
    )


# ---- manifest generated by scanning pages/ ----


def _title_of(md_path: Path, fallback: str) -> str:
    try:
        for line in md_path.read_text(encoding="utf-8").splitlines():
            m = re.match(r"#\s+(.+)", line.strip())
            if m:
                return m.group(1).strip()
    except OSError:
        pass
    return fallback


def _scan_children(dir_path: Path, rel_prefix: str) -> list[dict]:
    subs = [d for d in dir_path.iterdir() if d.is_dir() and (d / "page.md").is_file()]
    subs.sort(key=lambda d: (d / "page.md").stat().st_ctime)
    children = []
    for d in subs:
        rel = f"{rel_prefix}/{d.name}/page.md"
        children.append(
            {
                "slug": d.name,
                "title": _title_of(d / "page.md", d.name),
                "file": rel,
                "children": _scan_children(d, f"{rel_prefix}/{d.name}"),
            }
        )
    return children


def build_manifest(proj: Path) -> dict:
    pages = _pages_dir(proj)
    metadata = read_metadata(proj)
    return {
        "schema_version": SCHEMA_VERSION,
        "title": _title_of(pages / "index.md", "Logbook"),
        "emoji": metadata.get("emoji", "🎯"),
        "updated_at": _now_iso(),
        "root": {
            "slug": ROOT_SLUG,
            "title": _title_of(pages / "index.md", "Logbook"),
            "file": "pages/index.md",
            "children": _scan_children(pages, "pages"),
        },
    }


def _walk(node: dict):
    yield node
    for child in node.get("children", []):
        yield from _walk(child)


def flatten_markdown(proj: Path, manifest: dict) -> str:
    root = logbook_root(proj)
    out = [f"# {manifest['title']}", ""]
    for node in _walk(manifest["root"]):
        text = (root / node["file"]).read_text(encoding="utf-8")
        out.append(re.sub(r"<!--.*?-->", "", text).strip())
        out.append("")
    return "\n".join(out)


def _ensure_viewer_files(proj: Path) -> None:
    root = logbook_root(proj)
    for fname in VIEWER_FILES:
        dest = root / fname
        src = VIEWER_DIR / fname
        if not dest.exists() and src.is_file():
            shutil.copy2(src, dest)


def write_site_files(proj: Path) -> dict:
    _ensure_viewer_files(proj)
    manifest = build_manifest(proj)
    root = logbook_root(proj)
    (root / "logbook.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    (root / "logbook.md").write_text(flatten_markdown(proj, manifest), encoding="utf-8")
    return manifest


# ---- creation ----


def create_logbook(
    title: str | None = None, space_id: str | None = None, emoji: str = "🎯"
) -> Path:
    proj = find_project_dir() or (Path.cwd() / PROJECT_DIR_NAME)
    title = title or proj.parent.name or "Experiment"
    root = logbook_root(proj)
    if (root / "pages" / "index.md").exists():
        raise LogbookError(
            f"A logbook already exists at {root}. Attach with `trackio logbook open`."
        )
    (root / "pages").mkdir(parents=True, exist_ok=True)
    (root / "pages" / "index.md").write_text(
        f"# {title}\n\n"
        "> Index of experiments. Click one to open its page. Edit this page "
        "freely — the table is just Markdown.\n\n"
        "## Experiments\n\n"
        f"{EXP_HEADER}\n{EXP_SEP}\n"
        "| planned | "
        'Log a finding with `trackio logbook note "..." --experiment "..."` |\n',
        encoding="utf-8",
    )
    write_metadata(
        proj, {"space_id": space_id, "emoji": emoji, "created_at": _now_iso()}
    )
    (proj / ".gitignore").write_text(
        "logbook/.sync_lock\nlogbook/.sync_pending\nlogbook/.sync.log\n",
        encoding="utf-8",
    )
    write_site_files(proj)
    return proj


# ---- safe append/create helpers ----


def _all_slugs(proj: Path) -> set[str]:
    slugs = {ROOT_SLUG}
    for d in _pages_dir(proj).rglob("*"):
        if d.is_dir() and (d / "page.md").is_file():
            slugs.add(d.name)
    return slugs


def _page_dir_for_slug(proj: Path, slug: str) -> Path | None:
    if slug == ROOT_SLUG:
        return _pages_dir(proj)
    for d in _pages_dir(proj).rglob("*"):
        if d.is_dir() and d.name == slug and (d / "page.md").is_file():
            return d
    return None


def _page_file_for_slug(proj: Path, slug: str) -> Path | None:
    if slug == ROOT_SLUG:
        return _pages_dir(proj) / "index.md"
    d = _page_dir_for_slug(proj, slug)
    return (d / "page.md") if d else None


def add_page(proj: Path, title: str, parent_slug: str = ROOT_SLUG) -> str:
    parent_dir = _page_dir_for_slug(proj, parent_slug)
    if parent_dir is None:
        raise LogbookError(f"No page with slug '{parent_slug}' in this logbook.")
    existing = _all_slugs(proj)
    base = _slugify(title)
    slug = base
    n = 2
    while slug in existing:
        slug = f"{base}-{n}"
        n += 1
    page_dir = parent_dir / slug
    page_dir.mkdir(parents=True, exist_ok=True)
    (page_dir / "page.md").write_text(f"# {title}\n", encoding="utf-8")
    return slug


def _insert_toc_row(text: str, row: str) -> str:
    lines = [ln for ln in text.split("\n") if "logbook note" not in ln]
    idx = next(
        (i for i, ln in enumerate(lines) if ln.strip().lower() == "## experiments"),
        None,
    )
    if idx is not None:
        j = idx + 1
        while j < len(lines) and not lines[j].strip().startswith("|"):
            j += 1
        if j >= len(lines):
            lines[idx + 1 : idx + 1] = ["", EXP_HEADER, EXP_SEP, row, ""]
            return "\n".join(lines)
        k = j
        while k < len(lines) and lines[k].strip().startswith("|"):
            k += 1
        lines.insert(k, row)
        return "\n".join(lines)
    block = ["", "## Experiments", "", EXP_HEADER, EXP_SEP, row, ""]
    h1 = next((i for i, ln in enumerate(lines) if ln.strip().startswith("# ")), None)
    at = (h1 + 1) if h1 is not None else len(lines)
    lines[at:at] = block
    return "\n".join(lines)


def set_experiment_status(proj: Path, slug: str, status: str) -> None:
    index = _pages_dir(proj) / "index.md"
    lines = index.read_text(encoding="utf-8").split("\n")
    for i, ln in enumerate(lines):
        if f"(#/{slug})" in ln and ln.strip().startswith("|"):
            cells = ln.split("|")
            if len(cells) >= 3:
                cells[1] = f" {status} "
                lines[i] = "|".join(cells)
            break
    index.write_text("\n".join(lines), encoding="utf-8")


def ensure_experiment(proj: Path, name: str, status: str | None = None) -> str:
    slug = _slugify(name)
    if slug in _all_slugs(proj):
        if status:
            set_experiment_status(proj, slug, status)
        return slug
    slug = add_page(proj, name, parent_slug=ROOT_SLUG)
    index = _pages_dir(proj) / "index.md"
    row = f"| {status or 'in-progress'} | [{name}](#/{slug}) |"
    index.write_text(
        _insert_toc_row(index.read_text(encoding="utf-8"), row), encoding="utf-8"
    )
    return slug


def _resolve_artifact(name: str) -> str:
    try:
        from trackio.sqlite_storage import SQLiteStorage

        project_and_name = name.split(":")[0] if ":" in name else name
        if "/" not in project_and_name:
            return f"**📦 Artifact** `{name}`"
        project, art_name = project_and_name.split("/", 1)
        manifest = SQLiteStorage.get_artifact_manifest(project, art_name)
        size = sum(entry.get("size", 0) for entry in manifest)
        gb = size / 1e9
        size_str = f"{gb:.2f} GB" if gb >= 0.01 else f"{size / 1e6:.1f} MB"
        return f"**📦 Artifact** `{name}` · {len(manifest)} files · {size_str}"
    except Exception:
        return f"**📦 Artifact** `{name}`"


def add_note(
    proj: Path,
    body: str,
    title: str | None = None,
    page_slug: str = ROOT_SLUG,
    links: list[str] | None = None,
    artifacts: list[str] | None = None,
) -> None:
    page_path = _page_file_for_slug(proj, page_slug)
    if page_path is None:
        raise LogbookError(f"No page with slug '{page_slug}' in this logbook.")
    links = list(links or [])
    artifacts = list(artifacts or [])
    links += re.findall(r"--link[=\s]+(\S+)", body)
    artifacts += re.findall(r"--artifact[=\s]+(\S+)", body)
    body = re.sub(r"--(?:link|artifact)[=\s]+\S+", "", body).strip()
    now = _now_iso()
    lines = ["", "---", ""]
    lines.append(f"### {title.strip() if title else 'Note'}")
    lines.append(f"<!-- entry ts={now} -->")
    lines.append(f"`{_human_time(now)}`")
    lines.append("")
    lines.append(body)
    lines.append("")
    for art in artifacts:
        lines.append(f"- {_resolve_artifact(art)}")
    for url in links:
        lines.append(f"- {url.strip()}")
    if artifacts or links:
        lines.append("")
    with page_path.open("a", encoding="utf-8") as f:
        f.write("\n".join(lines))


def status_text(proj: Path) -> str:
    manifest = write_site_files(proj)
    metadata = read_metadata(proj)
    lines = [
        f"🎯  {manifest['title']}",
        f"    dir     {logbook_root(proj)}",
    ]
    if metadata.get("space_id"):
        state = "auto-syncing" if metadata.get("autosync") else "not published"
        lines.append(f"    space   {metadata['space_id']}  ({state})")

    def render(node, depth):
        marker = "•" if depth else "▸"
        lines.append(f"    {'  ' * depth}{marker} {node['title']}  ({node['slug']})")
        for child in node.get("children", []):
            render(child, depth + 1)

    lines.append("")
    lines.append("  Pages:")
    render(manifest["root"], 0)
    return "\n".join(lines)


# ---- serve / publish / sync ----


def serve(port: int = 7861, open_browser: bool = True) -> None:
    import functools
    import http.server
    import socketserver
    import webbrowser

    proj = require_project_dir()
    write_site_files(proj)
    handler = functools.partial(
        http.server.SimpleHTTPRequestHandler, directory=str(logbook_root(proj))
    )
    socketserver.TCPServer.allow_reuse_address = True
    with socketserver.TCPServer(("", port), handler) as httpd:
        url = f"http://localhost:{port}/"
        print(f"Serving logbook at {url}\nPress Ctrl+C to stop.")
        if open_browser:
            try:
                webbrowser.open(url)
            except Exception:
                pass
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            print("\nStopped.")


def _readme(manifest: dict) -> str:
    emoji = manifest.get("emoji", "🎯")
    title = manifest["title"].replace('"', "'")
    return (
        f"---\ntitle: {title}\nemoji: {emoji}\ncolorFrom: yellow\ncolorTo: red\n"
        "sdk: static\npinned: false\ntags:\n - trackio\n - trackio-logbook\n"
        " - open-experiment\n---\n\n"
        f"# {manifest['title']}\n\nAn open experiment logbook, published with "
        "[Trackio](https://github.com/gradio-app/trackio).\n"
    )


def _push(proj: Path, hf_token: str | None = None) -> str:
    import huggingface_hub

    metadata = read_metadata(proj)
    space_id = metadata["space_id"]
    manifest = write_site_files(proj)
    (logbook_root(proj) / "README.md").write_text(_readme(manifest), encoding="utf-8")
    api = huggingface_hub.HfApi(token=hf_token)
    huggingface_hub.create_repo(
        space_id,
        repo_type="space",
        space_sdk="static",
        exist_ok=True,
        token=hf_token,
    )
    api.upload_folder(
        repo_id=space_id,
        repo_type="space",
        folder_path=str(logbook_root(proj)),
        commit_message=f"Update logbook: {manifest['title']}",
        ignore_patterns=[".sync_lock", ".sync_pending", ".sync.log"],
    )
    return f"https://huggingface.co/spaces/{space_id}"


def publish(space_id: str | None = None, hf_token: str | None = None) -> str:
    proj = require_project_dir()
    metadata = read_metadata(proj)
    space_id = space_id or metadata.get("space_id")
    if not space_id:
        raise LogbookError(
            "No Space id. Provide one: trackio logbook publish <username/space>"
        )
    metadata["space_id"] = space_id
    metadata["autosync"] = True
    write_metadata(proj, metadata)
    return _push(proj, hf_token=hf_token)


def is_autosync(proj: Path) -> bool:
    metadata = read_metadata(proj)
    return bool(metadata.get("autosync") and metadata.get("space_id"))


def trigger_autosync(proj: Path) -> None:
    import subprocess
    import sys

    if not is_autosync(proj):
        return
    (logbook_root(proj) / ".sync_pending").write_text("1", encoding="utf-8")
    try:
        log = open(logbook_root(proj) / ".sync.log", "a", encoding="utf-8")
        subprocess.Popen(
            [sys.executable, "-m", "trackio.cli", "logbook", "_sync"],
            cwd=str(proj.parent),
            stdout=log,
            stderr=subprocess.STDOUT,
            start_new_session=True,
        )
    except Exception:
        pass


def sync_worker(debounce: float = 2.5) -> None:
    import fcntl
    import time

    proj = find_project_dir()
    if proj is None:
        return
    root = logbook_root(proj)
    lock = open(root / ".sync_lock", "w")
    try:
        fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
    except OSError:
        return
    try:
        pending = root / ".sync_pending"
        while pending.exists():
            pending.unlink()
            time.sleep(debounce)
            try:
                _push(proj)
            except Exception:
                pass
    finally:
        try:
            fcntl.flock(lock, fcntl.LOCK_UN)
        finally:
            lock.close()
