name: Unit Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
        enable-cache: true
        
    - name: Install system dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update -qy
        sudo apt-get install -qy ffmpeg
        
    - name: Install system dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        # FFmpeg installation for Windows (using chocolatey)
        choco install ffmpeg -y
        
    - name: Install Python dependencies
      run: |
        uv pip install --system -e .[dev,tensorboard]
        uv pip install --system pytest
        
    - name: Run tests (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        pytest
        
    - name: Run tests (Windows - skip concurrent test)
      if: matrix.os == 'windows-latest'
      run: |
        pytest -k "not test_concurrent_database_access_without_errors" 